title: Not the Rensselaer Handbook
description: The classic handbook for RPI
theme: just-the-docs

# url: https://just-the-docs.github.io

# Split pages into sections that can be searched individually
# Supports 1 - 6, default: 2
search.heading_level: 3